Customer success Platform Backend.
chintans/customer-success-platform pull request #10
Opened 2024-03-28 14:55 UTC by Rahul-Maity

2024-04-03 05:44 UTC, rahul-COD3 commented on Promact.CustomerSuccess.Platform/Controllers/AccountController.cs
> +//}
Commented code should not be in PR,

2024-04-03 06:14 UTC, rahul-COD3 requested changes

2024-04-03 06:14 UTC, rahul-COD3 commented on Promact.CustomerSuccess.Platform/Controllers/EmailController.cs
> +            smtp.Connect("smtp.gmail.com", 587, SecureSocketOptions.StartTls);
Don't put sensitive details in code

2024-04-03 06:14 UTC, rahul-COD3 commented on Promact.CustomerSuccess.Platform/Controllers/EmailController.cs
> +        public List<Stakeholder> Stakeholders { get; set; }
same as above

2024-04-03 06:14 UTC, rahul-COD3 commented on Promact.CustomerSuccess.Platform/Controllers/EmailController.cs
> +    public class EmailRequestBudget
Don't put classes randomly

2024-04-03 06:14 UTC, rahul-COD3 commented on Promact.CustomerSuccess.Platform/Entities/Project.cs
> +        //public virtual ICollection<ProjectResources>? ProjectResources { get; set; }
Commented code should not be in PR,

2024-04-03 06:20 UTC, rahul-COD3 commented on Promact.CustomerSuccess.Platform/Services/DocumentVersionService.cs
> +            DocumentVersionDto,
Fix the formatting

2024-04-03 06:22 UTC, rahul-COD3 commented on Promact.CustomerSuccess.Platform/Entities/Sprint.cs
> -    public class Sprint : AuditedAggregateRootWithUser<Guid, ApplicationUser>
Why you removed  AuditedAggregateRootWithUser<Guid, ApplicationUser>

2024-04-03 06:24 UTC, rahul-COD3 commented on Promact.CustomerSuccess.Platform/Services/Dtos/CreateProjectResourcesDto.cs
> +
Fix formatting

2024-04-03 06:31 UTC, rahul-COD3 commented on Promact.CustomerSuccess.Platform/Controllers/AccountController.cs
> +            await HttpContext.ChallengeAsync(Auth0Constants.AuthenticationScheme, authenticationProperties);
Use dependency injection for accessing HttpContext

2024-04-03 06:37 UTC, rahul-COD3 commented on Promact.CustomerSuccess.Platform/Controllers/EmailController.cs
> +                SendEmail(stakeholder.Contact, "Audit History Updated", emailBody);
Lack of async await

2024-04-03 06:38 UTC, rahul-COD3 commented on Promact.CustomerSuccess.Platform/Controllers/EmailController.cs
> +                SendEmail(stakeholder.Contact, "ApprovedTeam History Updated", emailBody);
Lack of async await

2024-04-03 06:38 UTC, rahul-COD3 commented on Promact.CustomerSuccess.Platform/Controllers/EmailController.cs
> +                SendEmail(stakeholder.Contact, "Project Scope Updates", emailBody);
same as above

2024-04-03 06:38 UTC, rahul-COD3 commented on Promact.CustomerSuccess.Platform/Controllers/EmailController.cs
> +                SendEmail(stakeholder.Contact, "Project Phase Milestone Updates", emailBody);
same as above

2024-04-03 06:46 UTC, rahul-COD3 commented on Promact.CustomerSuccess.Platform/Entities/PhaseMilestone.cs
> +        //public virtual ICollection<Sprint>? Sprints { get; set; }
Why did you remove the public virtual ICollection<Sprint> Sprints { get; set; }?

2024-04-04 16:43 UTC, Rahul-Maity commented
fixed formatting and integrated email in service.

2024-04-04 16:45 UTC, Rahul-Maity reviewed
Email service

2024-04-06 06:11 UTC, Rahul-Maity commented on Promact.CustomerSuccess.Platform/Controllers/AccountController.cs
> +//}
Resolved

2024-04-06 06:12 UTC, Rahul-Maity commented on Promact.CustomerSuccess.Platform/Controllers/AccountController.cs
> +}
Resolved

2024-04-06 06:12 UTC, Rahul-Maity commented on Promact.CustomerSuccess.Platform/Controllers/EmailController.cs
> +            if (!ModelState.IsValid) { return BadRequest(ModelState); }
removed controller

2024-04-06 06:13 UTC, Rahul-Maity commented on Promact.CustomerSuccess.Platform/Controllers/EmailController.cs
> +        //public AuditHistory AuditData { get; set; }
Resolved

2024-04-06 06:13 UTC, Rahul-Maity commented on Promact.CustomerSuccess.Platform/Controllers/HomeController.cs
> +        //return Redirect("http://localhost:4200/");
Resolved

2024-04-06 06:14 UTC, Rahul-Maity commented on Promact.CustomerSuccess.Platform/Entities/Sprint.cs
> +
Fixed

2024-04-06 06:14 UTC, Rahul-Maity commented on Promact.CustomerSuccess.Platform/Controllers/EmailController.cs
> +            smtp.Connect("smtp.gmail.com", 587, SecureSocketOptions.StartTls);
Resolved

2024-04-06 06:14 UTC, Rahul-Maity commented on Promact.CustomerSuccess.Platform/Controllers/EmailController.cs
> +        public List<Stakeholder> Stakeholders { get; set; }
Resolved

2024-04-06 06:15 UTC, Rahul-Maity commented on Promact.CustomerSuccess.Platform/Controllers/EmailController.cs
> +    public class EmailRequestBudget
Resolved

2024-04-06 06:15 UTC, Rahul-Maity commented on Promact.CustomerSuccess.Platform/Entities/Project.cs
> +        //public virtual ICollection<ProjectResources>? ProjectResources { get; set; }
Resolved

2024-04-06 06:16 UTC, Rahul-Maity commented on Promact.CustomerSuccess.Platform/Services/DocumentVersionService.cs
> +            DocumentVersionDto,
Fixed formatting

2024-04-06 06:16 UTC, Rahul-Maity commented on Promact.CustomerSuccess.Platform/Entities/Sprint.cs
> -    public class Sprint : AuditedAggregateRootWithUser<Guid, ApplicationUser>
Resolved

2024-04-06 06:17 UTC, Rahul-Maity commented on Promact.CustomerSuccess.Platform/Controllers/AccountController.cs
> +            await HttpContext.ChallengeAsync(Auth0Constants.AuthenticationScheme, authenticationProperties);
Resolved

2024-04-06 06:17 UTC, Rahul-Maity commented on Promact.CustomerSuccess.Platform/Controllers/EmailController.cs
> +                SendEmail(stakeholder.Contact, "Audit History Updated", emailBody);
Resolved

2024-04-06 06:17 UTC, Rahul-Maity commented on Promact.CustomerSuccess.Platform/Controllers/EmailController.cs
> +                SendEmail(stakeholder.Contact, "ApprovedTeam History Updated", emailBody);
Resolved

2024-04-06 06:18 UTC, Rahul-Maity commented on Promact.CustomerSuccess.Platform/Controllers/EmailController.cs
> +                SendEmail(stakeholder.Contact, "Project Scope Updates", emailBody);
Resolved

2024-04-06 06:18 UTC, Rahul-Maity commented on Promact.CustomerSuccess.Platform/Controllers/EmailController.cs
> +                SendEmail(stakeholder.Contact, "Project Phase Milestone Updates", emailBody);
Resolved

2024-04-06 06:20 UTC, Rahul-Maity commented on Promact.CustomerSuccess.Platform/Entities/PhaseMilestone.cs
> +        //public virtual ICollection<Sprint>? Sprints { get; set; }
Resolved

2024-04-06 06:20 UTC, Rahul-Maity commented on Promact.CustomerSuccess.Platform/Services/EscalationMatrixService.cs
> +
Resolved

2024-04-25 05:45 UTC, closed without merging