Backend for Customer Success Platform
chintans/customer-success-platform pull request #3
Opened 2024-03-28 13:52 UTC by Priyanshu-792

To perform all the cruds successfully.

2024-04-02 04:26 UTC, chintans requested changes
naming conventions in generating migrations are wrong, we use pascle casing and no spaces in the names.

2024-04-02 04:26 UTC, chintans commented on Promact.CustomerSuccess.Platform/Controllers/EmailController.cs
> +    public class EmailController : ControllerBase
In abp.io we don't create controllers. Review this please https://docs.abp.io/en/abp/latest/Tutorials/Part-1?UI=MVC&DB=EF#bookappservice

2024-04-02 04:26 UTC, chintans commented on Promact.CustomerSuccess.Platform/Controllers/EmailController.cs
> +        private const string EmailHost = "smtp.gmail.com";
Don't put sensitive details in code

2024-04-02 04:26 UTC, chintans commented on Promact.CustomerSuccess.Platform/Controllers/EmailController.cs
> +        public IActionResult SendEmails([FromBody] List<EmailDto> emails)
Lack of async await

2024-04-02 04:26 UTC, chintans commented on Promact.CustomerSuccess.Platform/Controllers/EmailController.cs
> +    public class EmailDto
Don't put classes randomly

2024-04-02 04:26 UTC, chintans commented on Promact.CustomerSuccess.Platform/Entities/ApprovedTeam.cs
> +    public class ApprovedTeam : AuditedAggregateRootWithUser<Guid, ApplicationUser>
What is the purpose of this table?

2024-04-02 04:26 UTC, chintans commented on Promact.CustomerSuccess.Platform/Entities/DetailedTimeline.cs
> +    public class DetailedTimeline : Entity<Guid>
What is the purpose of this table?

2024-04-02 04:26 UTC, chintans commented on Promact.CustomerSuccess.Platform/Entities/EscalationMatrix.cs
> +        public string Name { get; set; }
What do you mean by Name here?

2024-04-02 04:26 UTC, chintans commented on Promact.CustomerSuccess.Platform/Entities/PhaseMilestone.cs
> +        public DateTime RevisedCompletionDate { get; set; }
What is the purpose of this field?

2024-04-02 04:26 UTC, chintans commented on Promact.CustomerSuccess.Platform/Entities/ProjectDescription.cs
> +    public class ProjectDescription : Entity<Guid>
Why is this a separate table for description? What is the benefit of keeping it in different tables?

2024-04-02 04:26 UTC, chintans commented on Promact.CustomerSuccess.Platform/Entities/ProjectResources.cs
> +        public string ResourceName { get; set; }
What is the purpose of this?

2024-04-02 04:26 UTC, chintans commented on Promact.CustomerSuccess.Platform/Entities/ProjectUpdates.cs
> +    public class ProjectUpdates : AuditedAggregateRootWithUser<Guid, ApplicationUser>
What is the purpose of this table?

2024-04-02 04:26 UTC, chintans commented on Promact.CustomerSuccess.Platform/Entities/RiskProfile.cs
> +        public string? RemedialSteps { get; set; }
Why RemedialSteps have been converted to a string field from a different table?

2024-04-02 04:26 UTC, chintans commented on Promact.CustomerSuccess.Platform/Entities/RiskProfile.cs
> +        public string? Description { get; set; }
What is the purpose of Description?

2024-04-02 04:26 UTC, chintans commented on Promact.CustomerSuccess.Platform/Entities/Scope.cs
> +    public class Scope : Entity<Guid>
I cannot understand creating tables with just a 1-to-1 relation between entities. correct me if I am wrong here

2024-04-02 04:26 UTC, chintans commented on Promact.CustomerSuccess.Platform/Entities/Sprint.cs
Now why did we remove link with Phased Milestone

2024-04-02 04:26 UTC, chintans commented on Promact.CustomerSuccess.Platform/Entities/StakeHolders.cs
> +    public class StakeHolders : Entity<Guid>
Who are the stakeholders? What is the purpose of this table?

2024-04-02 04:26 UTC, chintans commented on Promact.CustomerSuccess.Platform/Migrations/20240313095405_projectBudget.cs
Why do we have a blank migration?

2024-04-02 04:26 UTC, chintans commented on Promact.CustomerSuccess.Platform/Migrations/20240313164936_document.cs
Why blank?

2024-04-02 04:26 UTC, chintans commented on Promact.CustomerSuccess.Platform/Migrations/20240313213528_Risk Profilings.cs
Again?

2024-04-02 04:26 UTC, chintans commented on Promact.CustomerSuccess.Platform/Migrations/20240314061342_PhaseMilestones.cs
Again?

2024-04-02 04:26 UTC, chintans commented on Promact.CustomerSuccess.Platform/Services/ClientFeedbackService.cs
> +            Guid,
Fix the formatting

2024-04-02 04:26 UTC, chintans commented on Promact.CustomerSuccess.Platform/Services/Dtos/CreateApprovedTeamDto.cs
> +    public class CreateApprovedTeamDto
Why have you not implemented IEntityDto here and other DTO classes?

2024-04-02 04:26 UTC, chintans commented on Promact.CustomerSuccess.Platform/Services/IApprovedTeamService.cs
Why empty?

2024-04-03 18:57 UTC, Priyanshu-792 commented on Promact.CustomerSuccess.Platform/Controllers/EmailController.cs
> +    public class EmailController : ControllerBase
Thank you sir for providing the reference.

2024-04-03 18:58 UTC, Priyanshu-792 commented on Promact.CustomerSuccess.Platform/Controllers/EmailController.cs
> +        private const string EmailHost = "smtp.gmail.com";
> Don't put sensitive details in code

Ok Sir thankyou for your feedback i will try to resolve this.

2024-04-04 05:49 UTC, Priyanshu-792 commented on Promact.CustomerSuccess.Platform/Controllers/EmailController.cs
> +        public IActionResult SendEmails([FromBody] List<EmailDto> emails)
I will implement it.

2024-04-04 05:50 UTC, Priyanshu-792 commented on Promact.CustomerSuccess.Platform/Controllers/EmailController.cs
> +    public class EmailDto
ok sir i will try to put it in the proper dto folder.

2024-04-04 05:57 UTC, Priyanshu-792 commented on Promact.CustomerSuccess.Platform/Entities/ApprovedTeam.cs
> +    public class ApprovedTeam : AuditedAggregateRootWithUser<Guid, ApplicationUser>
It was present in our guidelines and requirements of the project, to store approved team for every project.

2024-04-04 06:06 UTC, Priyanshu-792 commented on Promact.CustomerSuccess.Platform/Migrations/20240313213528_Risk Profilings.cs
Actually sir , initially i was not aware when to create migration , so any changes i was doing in backend code i was creating migration thinking that it is a convention to do it. But anyways, i will definitely take care of it not to provide any empty migration further.

2024-04-04 06:06 UTC, Priyanshu-792 commented on Promact.CustomerSuccess.Platform/Migrations/20240314061342_PhaseMilestones.cs
I will rectify it sir.

2024-04-04 06:06 UTC, Priyanshu-792 commented on Promact.CustomerSuccess.Platform/Services/ClientFeedbackService.cs
> +            Guid,
ok

2024-04-25 05:39 UTC, closed without merging